version: '3.8'

services:
  app-hub-assistance-ai:
    build:
      context: .
      args:
        - OPENAI_API_KEY=${OPENAI_API_KEY}
    expose:
      - "3000"
    networks:
      reverse-proxy-net:
        aliases:
          - bakerlab-ai-app
      bakerlab-ai-net:
    env_file:
      - .env
      - .env_db
    environment:
      - HOSTNAME=hubassistants-ia.baker-park.com
      - NEXTAUTH_URL=https://hubassistants-ia.baker-park.com
      - NEXTAUTH_URL_INTERNAL=http://localhost:3000
      - NEXTAUTH_TRUSTED_HOSTS=hubassistants-ia.baker-park.com,localhost
      # Force secure cookies
      - NEXTAUTH_COOKIE_SECURE=true
    depends_on:
      - db-hub-assistance-ai
    restart: unless-stopped

  db-hub-assistance-ai:
    image: mariadb:10.6
    env_file:
      - .env_db
    networks:
      - bakerlab-ai-net
    expose:
      - "3306"
    volumes:
      - mysql_data-hub-assistance-ai:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

volumes:
  mysql_data-hub-assistance-ai:
    name: igensia_mysql_data-hub-assistance-ai

networks:
  reverse-proxy-net:
    external: true
  bakerlab-ai-net:
