version: '3.8'

services:
  app-hub-assistance-ai:
    build:
      context: .
      args:
        - OPENAI_API_KEY=${OPENAI_API_KEY}
    expose:
      - "3000"
    ports:
      - "3000:3000"
    env_file:
      - .env
      - .env_db
    environment:
      - HOSTNAME=hubassistants-ia.baker-park.com
      - NEXTAUTH_URL=https://hubassistants-ia.baker-park.com
      - NEXTAUTH_URL_INTERNAL=http://localhost:3000
      - NEXTAUTH_TRUSTED_HOSTS=hubassistants-ia.baker-park.com,localhost
      # Force secure cookies
      - NEXTAUTH_COOKIE_SECURE=true
    depends_on:
      - db-hub-assistance-ai
    restart: unless-stopped

  db-hub-assistance-ai:
    image: mariadb:10.6
    env_file:
      - .env_db
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql_data-hub-assistance-ai:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

volumes:
  mysql_data-hub-assistance-ai:
    name: igensia_mysql_data-hub-assistance-ai
